suppressMessages(library(plyr))
suppressMessages(library(dplyr))

# INPUT - uses two enzyme list files generated by enzymeX, required .txt and
# that the first 7 characters of the filename is the plasmid name.
# TODO - input requirements are a bit specific, can I make them more general

# TODO - find some way to call digest on .fa file from R
# TODO - fragment size difference analysis -- in progress

# Registering files to process
# From inside R
# ARGS <- list.files(pattern = ".txt")
# From the command line
ARGS <- commandArgs(trailingOnly = TRUE)

# Generate preproccessing script, run it, then remove it
writeLines("sed '1,3d; /^$/,$d; /-/d; />/d' $1 \\
  | awk '{ print $1, NF-2 }' > num_site_$1
sed '1,3d; /^$/,$d; /-/d; />/d' $1 \\
  | cut -f1,3- > sites_$1",
           con = "pre-proc.sh")
system("chmod +x pre-proc.sh")
lapply(ARGS,
       function(x){
         system(paste("./pre-proc.sh ", x))
       })
system("rm pre-proc.sh")

# Analysis of number of sites
NUM_SITES <- list.files(pattern = "num_site_")
ns.l <- lapply(NUM_SITES,
               function(x){
                 read.delim(x,
                            sep = " ",
                            header = FALSE)
               })
system("rm num_site_*")
names(ns.l) <- NUM_SITES
ns.df <- join(ns.l[[1]],
              ns.l[[2]],
              by = "V1")
ns.df[is.na(ns.df)] <- 0
names(ns.df) <- c("RE", substr(ARGS[1], 1, 7), substr(ARGS[2], 1, 7))
write.csv(ns.df[ns.df[,2] != ns.df[,3],],
          file = "sites-with-diff-freq.csv",
          quote = FALSE,
          row.names = FALSE) 

# Fragment size differences
# 
# Need the size of each plasmid
# the length of the fasta file
# nchar(paste(scan(paste(tolower(substr(ARGS[1], 1, 7)), 
#                        ".fasta", 
#                        sep = ""),
#                  what = "character",
#                  skip = 1), 
#             collapse = ""))

# Reading in sites_* files
scan(file = "sites_pNick93_enz_list.txt",
     what = "char")

